name: nyxx_interactions
version: 4.1.0
description: Nyxx Interactions Module. Discord library for Dart. Simple, robust framework for creating discord bots for Dart language.
homepage: https://github.com/nyxx-discord/nyxx
repository: https://github.com/nyxx-discord/nyxx
documentation: https://nyxx.l7ssha.xyz
issue_tracker: https://github.com/nyxx-discord/nyxx/issues
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  logging: ^1.0.1
  nyxx:
    git:
      url: https://github.com/NDSo/nyxx.git
      ref: next

dev_dependencies:
  test: ^1.19.0
  mockito: ^5.0.16
  build_runner: ^2.1.4
  lints: ^1.0.1
  coverage: ^1.0.3
